### ISSUE TITLE
Create a French translated version of the web documentation. 

### ISSUE THREAD

**Issue by hbshrestha** [SPLATteam/splat-tutorial#14]
This is to be tested once the documentation is finalized.

**Comment by lys1900** [comment]
@hbshrestha 
There are two ways of doing this, I tried out the first one and am in the midst of trying the second: https://splat-tutorial.readthedocs.io/en/french_v/ (placeholder)
1. create a separate branch e.g. french, and set it as active, never merge it to main (english)
2. set up a separate project for french.
I don't suppose we will have many versions of the SPLAT interface, therefore tending towards simply using option 1 as it seems easier to set up. The downside of this is just, the link for the french version will end with /en/french rather than /fr/latest

**Comment by hbshrestha** [comment]
Himalaya and Yunshu to test Python script for an API for language translation without affecting the special text such as links, cells, and button names.

**Comment by hbshrestha** [comment]
Tried to use DeepL API. However, it is not feasible without having a DeepL API account. Need credit card even for a free account.

**Comment by lys1900** [comment]
Code is done and merged
